.install_babashka: &install_babashka
  - bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
  - bb --version

variables:
  GITLIBS: .gitlibs
  TZ: "Asia/Singapore"

cache:
  untracked: true
  paths:
    - .m2/
    - .gitlibs/
    - .cpcache/

stages:
  - test

test:
  stage: test
  image: clojure:latest
  tags:
    - server
  before_script:
    - apt-get update && apt-get install -y curl
    - *install_babashka
  script:
    - bb test
